name: sticker_example
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  p_sticker:
    path: ../p_sticker

  shrine_images: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    # - assets/sticker/

    - packages/p_sticker/sticker/dm_e_01.png
    - packages/p_sticker/sticker/dm_e_02.png
    - packages/p_sticker/sticker/dm_e_03.png
    - packages/p_sticker/sticker/dm_e_04.png
    - packages/p_sticker/sticker/dm_e_05.png
    - packages/p_sticker/sticker/dm_e_06.png
    - packages/p_sticker/sticker/dm_e_07.png
    - packages/p_sticker/sticker/dm_e_08.png
    - packages/p_sticker/sticker/dm_e_09.png
    - packages/p_sticker/sticker/dm_e_10.png
    - packages/p_sticker/sticker/dm_e_11.png
    - packages/p_sticker/sticker/dm_e_12.png
    - packages/p_sticker/sticker/dm_e_13.png
    - packages/p_sticker/sticker/dm_e_14.png
    - packages/p_sticker/sticker/dm_e_15.png
    - packages/p_sticker/sticker/dm_e_16.png
    - packages/p_sticker/sticker/dm_e_17.png
    - packages/p_sticker/sticker/dm_e_18.png
    - packages/p_sticker/sticker/dm_e_19.png
    - packages/p_sticker/sticker/dm_e_20.png
    - packages/p_sticker/sticker/dm_e_21.png
    - packages/p_sticker/sticker/dm_e_22.png
    - packages/p_sticker/sticker/dm_e_23.png
    - packages/p_sticker/sticker/dm_e_24.png
    - packages/p_sticker/sticker/dm_e_25.png
    - packages/p_sticker/sticker/dm_e_26.png
    - packages/p_sticker/sticker/dm_e_27.png
    - packages/p_sticker/sticker/dm_e_28.png
    - packages/p_sticker/sticker/dm_e_29.png
    - packages/p_sticker/sticker/dm_e_30.png
    - packages/p_sticker/sticker/dm_e_31.png
    - packages/p_sticker/sticker/dm_e_32.png
    - packages/p_sticker/sticker/dm_e_33.png
    - packages/p_sticker/sticker/dm_e_34.png
    - packages/p_sticker/sticker/dm_e_35.png
    - packages/p_sticker/sticker/dm_e_36.png
    - packages/p_sticker/sticker/dm_e_37.png
    - packages/p_sticker/sticker/dm_e_38.png
    - packages/p_sticker/sticker/dm_e_39.png
    - packages/p_sticker/sticker/dm_e_40.png
    - packages/p_sticker/sticker/dm_e_41.png
    - packages/p_sticker/sticker/dm_e_42.png
    - packages/p_sticker/sticker/dm_e_43.png
    - packages/p_sticker/sticker/dm_e_44.png
    - packages/p_sticker/sticker/dm_e_45.png
    - packages/p_sticker/sticker/dm_e_46.png
    - packages/p_sticker/sticker/dm_e_47.png
    - packages/p_sticker/sticker/dm_e_48.png
    - packages/p_sticker/sticker/dm_e_49.png
    - packages/p_sticker/sticker/dm_e_50.png
    - packages/p_sticker/sticker/dm_e_51.png
    - packages/p_sticker/sticker/dm_e_52.png
    - packages/p_sticker/sticker/dm_e_53.png
    - packages/p_sticker/sticker/dm_e_54.png
    - packages/p_sticker/sticker/dm_e_55.png
    - packages/p_sticker/sticker/dm_e_56.png
    - packages/p_sticker/sticker/dm_e_57.png
    - packages/p_sticker/sticker/dm_e_58.png
    - packages/p_sticker/sticker/dm_e_59.png
    - packages/p_sticker/sticker/dm_e_60.png
    - packages/p_sticker/sticker/dm_e_61.png
    - packages/p_sticker/sticker/dm_e_62.png
    - packages/p_sticker/sticker/dm_e_63.png
    - packages/p_sticker/sticker/dm_e_64.png
    - packages/p_sticker/sticker/dm_e_65.png
    - packages/p_sticker/sticker/dm_e_66.png
    - packages/p_sticker/sticker/dm_e_67.png
    - packages/p_sticker/sticker/dm_e_68.png
    - packages/p_sticker/sticker/dm_e_69.png
    - packages/p_sticker/sticker/dm_e_70.png
    - packages/p_sticker/sticker/dm_e_71.png
    - packages/p_sticker/sticker/dm_e_72.png
    - packages/p_sticker/sticker/dm_e_73.png
    - packages/p_sticker/sticker/dm_e_74.png
    - packages/p_sticker/sticker/dm_e_75.png
    - packages/p_sticker/sticker/dm_e_76.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
